### PR TITLE
Add --from-wei and allow eth|ether as unit

### PR DESCRIPTION
**Pull request by nanexcool**

### CODE REVIEW

**Comment by dbrock** [comment]
I wonder if this should be called `--to-eth` instead?

**Comment by nanexcool** [comment]
I'm going by the Web3 API, which has `toWei` and `fromWei`

**Comment by dbrock** [comment]
But what if you also want `--to-gwei`?

**Comment by dbrock** [comment]
Okay this probably makes sense. :D

**Pull request merged**
